### ISSUE TITLE
[epic] Research visualization libraries for time series

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#1]
Compare the various visualization libraries to render the time series data. Include the following data for each library: 

* Library source
* Screenshots
* Description
* License
* Comments.

**RESULTS**: see [this spreadsheet](https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0)

**Comment by rufuspollock** [comment]
@kittdotech I do want to distinguish here between:

- Quickfire research where you can put this stuff into an issue with the info. This covers:
  - libraries
  - particular line chart styles or approaches
- Jekyll repo which is for actual live demos with real data e.g. doing a chart with plotly or d3

**Comment by kittdotech** [comment]
Yes I will update

**Comment by rufuspollock** [comment]
FIXED. See related issues and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
