### ISSUE TITLE
Research AMCharts

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#10]
# [AMCharts](https://www.amcharts.com)

amCharts is undoubtedly one of the most beautiful charting libraries out there. It perfectly segregates itself into 3 independent charts — JavaScript Charts, Maps Charts (amMaps), and Stock charts.

It provides features like loading icons or photos on top of your map, heatmaps, drawing lines, and adding text on maps, zooming and others.

amCharts uses SVG to render charts that work in modern browsers only. These charts may not work properly below Internet Explorer 9.

https://www.amcharts.com/download/
 * License
   * Free with a link or commercial
   * Free Version: https://github.com/amcharts/amcharts3
 * Size : 3.2 MB
 * Chart Features:
   * Zoomable: Yes
   * Hoverable: Yes, support hoverable
   * Overview + Detail: Selection of overview & detail is available.
   * Range pan: Yes available.

* Screenshots
![amchart1](https://cloud.githubusercontent.com/assets/12853878/20529489/53a88a6c-b0f6-11e6-8c5e-ad734f195b19.png)

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
