### ISSUE TITLE
Research ChartJS

### ISSUE THREAD

**Issue by rufuspollock** [datopian/line-charts#2]
ChartJS charts are responsive by default. They work well in mobiles and tablets.

http://www.chartjs.org/

*  https://github.com/chartjs/Chart.js
 * Github star: 26,389
* License: MIT
* Size: 319 kb
* Chart features
  * Zoomable:No
  * Hoverable: No
  * Overview + Detail: No
  * Range pan: No
* Mixed chart types, Easily Animate Chart & Responsive

![chartjs](https://cloud.githubusercontent.com/assets/12853878/20522487/975a70ec-b0d6-11e6-937a-02adb31de0c5.png)

**Comment by kittdotech** [comment]
# [chartjs](http://www.chartjs.org/)

ChartJS charts are responsive by default. They work well in mobiles and tablets.

## Source
 * https://github.com/chartjs/Chart.js
 * Github star: 26, 389

## License
 * MIT
## Size (Library)
* 319 kb

## Zoomable
Yes, support zooming

## Hoverable
Yes, support hoverable

## Overview + Detail
 * Selection of overview & detail is available.

## Range pan
 * Yes available.
## Screenshots
![chartjs](https://cloud.githubusercontent.com/assets/12853878/20522487/975a70ec-b0d6-11e6-937a-02adb31de0c5.png)

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
