### ISSUE TITLE
Check out bokeh (not JS but produces JS)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/line-charts#22]
http://bokeh.pydata.org/

http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#userguide-charts

**Comment by rufuspollock** [comment]
@anuveyatsu can you estimate how long it would take you to create a bokeh example. I imagine this would be python script code and then saving output JS + HTML that bokeh produces to the repo.

If this would be quick (say <= 2h) then worth doing to get a sense of this lib too.

**Comment by anuveyatsu** [comment]
@rgrp yes, I think should be around 2h. Will do it.
