### ISSUE TITLE
Research D3.js

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#3]
[D3.js](https://d3js.org/)

D3.js is a JavaScript library for manipulating documents based on data. D3 helps you bring data to life using HTML, SVG, and CSS.

* https://github.com/d3/d3
* Github star: 57,134
* License: BSD
* Size: 500 KB
* Chart Features:
  * Zoomable: Yes
  * Hoverable: Yes
  * Overview + Detail: Yes
  * Range pan: Yes

Projects based on [d3.js](https://d3js.org/)

**Dimple**

[Dimple on Git](https://github.com/PMSI-AlignAlytics/dimple/)

- Example
[Line Coloring](http://dimplejs.org/advanced_examples_viewer.html?id=advanced_dynamic_line_color)

- Screenshots & Link
![Line Graph](https://trello-attachments.s3.amazonaws.com/57fba5c106e4a5b96245157e/582d84a38b38ccb166c14a60/da472122cfb85d595e9c3a77924f93e8/Screenshot_from_2016-11-18_19-12-40.png) 

**DC.js**

[DC.js on Git](https://github.com/dc-js/dc.js)

- Examples
[Interactive Chart](http://dc-js.github.io/dc.js/)

- Screenshots
![Customize Range](https://trello-attachments.s3.amazonaws.com/57fba5c106e4a5b96245157e/582d84a38b38ccb166c14a60/8647ebaea5cf20cd25201ecacfb35f77/Screenshot_from_2016-11-18_19-36-14.png) 
![Pan Range](https://trello-attachments.s3.amazonaws.com/57fba5c106e4a5b96245157e/582d84a38b38ccb166c14a60/50cbb843f8e6656aa879ce12434c0209/Screenshot_from_2016-11-18_19-36-58.png) 

**D3-Timeseries**
[Interactive Visualization](http://mcaule.github.io/d3-timeseries/)

- Screenshots
![Range selector & pan](https://trello-attachments.s3.amazonaws.com/57fba5c106e4a5b96245157e/582d84a38b38ccb166c14a60/e60fe564e1f9fe4726cae79d56b5366d/Screenshot_from_2016-11-18_20-01-23.png)

**Comment by kittdotech** [comment]
Moved to description

**Comment by kittdotech** [comment]
Moved to description

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
