### ISSUE TITLE
Add link to https://rgrp.github.io/line-charts to the repo

### ISSUE THREAD

**Issue by domoritz** [datopian/line-charts#33]
So that it's easy to see the examples.

**Comment by domoritz** [comment]
I meant here 😄 

<img width="1085" alt="screen shot 2016-12-07 at 09 36 21" src="https://cloud.githubusercontent.com/assets/589034/20979194/b8bd1ae2-bc60-11e6-8c07-9cd8eeefd2f4.png">

**Comment by rufuspollock** [comment]
@domoritz 😉  - fixed and thanks for the suggestion!
