### ISSUE TITLE
Research plotly

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#4]
[plotly](https://plot.ly/)

Plot.ly is differentiated by being an online tool for doing analytics and visualization. It has robust API’s and includes one for python. Browsing the website, you’ll see that there are lots of very rich, interactive graphs.
You’ll need to follow the docs to get your API key set up. Once you do, it seems to all work pretty seamlessly. 
Plotly integrates pretty seamlessly with pandas. I also will give a shout out to them for being very responsive to an email question I had. I appreciate their timely reply.

* https://github.com/plotly/plotly.js
* Github star: 57,134
* License: MIT
* Size: 500 KB
* Chart Features:
  * Zoomable: Yes
  * Hoverable: Yes
  * Overview + Detail: Yes
  * Range pan: Yes
  * Example Click [here](https://plot.ly/pandas/time-series/#time-series-of-pandas-dateframe) for interactive visualization.

Screenshots
![plotly1](https://cloud.githubusercontent.com/assets/12853878/20530573/d5b3b6a0-b0f9-11e6-972c-61d67c67620b.png)

**Comment by kittdotech** [comment]
Moved to description

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
