### ISSUE TITLE
Research Vega

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#5]
[vega](https://vega.github.io/)
Vega is a declarative format for creating, saving, and sharing visualization designs. With Vega, visualizations are described in JSON, and generate interactive views using either HTML5 Canvas or SVG.

VEGA-LITE provides a higher-level grammar for visual analysis, comparable to ggplot or Tableau, that generates complete Vega specifications.

* https://github.com/vega/vega
* License: BSD
* Github star: 4451
* Size:  215 KB
* Chart Features
  * Zoomable: Yes
  * Hoverable: Yes
  * Overview + Detail: Yes
  * Range pan: Yes
  * For more you can visit [here](http://vega.github.io/vega-editor/index.html?mode=vega&spec=overview+detail)
Screenshots
![vega](https://cloud.githubusercontent.com/assets/12853878/20523686/4018dc00-b0dc-11e6-80f5-d842aa07ebd6.png)

![vega](https://cloud.githubusercontent.com/assets/12853878/20534474/58c7ace2-b107-11e6-846d-e4b85a1992d1.png)

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
