### ISSUE TITLE
Research Highcharts

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#6]
[Highcharts](http://www.highcharts.com/)

Highcharts JS is another very popular library for building graphs. It comes loaded with many different types of cool animations that are sufficient to attract many eyeballs to your website. Just like other libraries, Highcharts comes with many pre-built graphs like spline, area, areaspline, column, bar, pie, scatter, etc.

One of the biggest advantages of using Highcharts JS is the compatibility with older browsers like Internet Explorer 6. Standard browsers use SVG for the graphics rendering. In legacy Internet Explorer, graphics are drawn using VML.

* https://github.com/highcharts/highcharts
* Github star: 5, 679
* License
  * Highcharts is free for non-commercial and personal use, with licenses only needed for commercial applications.
* Size: 4 MB
* Chart Features
  * Zoomable: Yes
  * Hoverable: Yes
  * Overview + Detail: Yes
  * Selection of overview: Yes
  * Range pan: Yes

Screenshots
![highcharts1](https://cloud.githubusercontent.com/assets/12853878/20532257/58fee0d4-b0ff-11e6-8429-4d7998fe1c5b.png)

**Comment by rufuspollock** [comment]
FIXED. Here and https://raw.githubusercontent.com/datasets/finance-vix/master/data/vix-daily.csv
