### ISSUE TITLE
Research Chartist

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#8]
[Chartist.js](http://gionkunz.github.io/chartist-js/)

Chartist.js provides beautiful responsive charts. Just like ChartJS, Chartist.js is also the product of the community that was frustrated by using highly priced JavaScript charting libraries. It uses SVG to render the charts. It can be controlled and customised through CSS3 media queries and Sass. Also, note that Chartist.js provides cool animations that will work only in modern browsers.

* https://github.com/gionkunz/chartist-js
* Github star: 8, 829
* License: MIT
* Size: 10 KB
* Zoomable: No
* Hoverable: No
* Overview + Detail: No
* Range pan: No
* It has the plugin, which can be extended.

Screenshots
![chartis](https://cloud.githubusercontent.com/assets/12853878/20532658/cf37891c-b100-11e6-9f52-c3093e12a67a.png)

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
