### ISSUE TITLE
Research MetricsGraphics

### ISSUE THREAD

**Issue by kittdotech** [datopian/line-charts#9]
# [MetricsGraphics](http://metricsgraphicsjs.org/)

MetricsGraphics.js is a library built on top of D3 that is optimized for visualizing and laying out time-series data.It provides a simple way to produce common types of graphics in a principled, consistent and responsive way. The library currently supports line charts, scatterplots, histograms, bar charts and data tables as well as features like rug plots and basic linear regression.

https://github.com/mozilla/metrics-graphics
* Github star: 6, 324
* License: MPL
* Size: 260 kb
* Chart Features
  * Zoomable: Yes, Using Addons
  * Hoverable: Yes, Using Addons
  * Overview + Detail: No
  * Range pan: No

Screenshots

![metricsgraphshot1](https://cloud.githubusercontent.com/assets/12853878/20523439/0234409c-b0db-11e6-877e-face7dc88309.png)

**Comment by rufuspollock** [comment]
FIXED. Here and https://docs.google.com/spreadsheets/d/1xDySkMm3tWM3eVg4jl7X8__gDn6REPidnx1w-Vw_45g/edit#gid=0
